// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_regex_selector_name
std::string cpp_regex_selector_name(const std::string x);
RcppExport SEXP KaggleHouse_cpp_regex_selector_name(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_regex_selector_name(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rep_na_num
NumericVector cpp_rep_na_num(NumericVector xin, int rep);
RcppExport SEXP KaggleHouse_cpp_rep_na_num(SEXP xinSEXP, SEXP repSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xin(xinSEXP);
    Rcpp::traits::input_parameter< int >::type rep(repSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rep_na_num(xin, rep));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rep_na_chr
CharacterVector cpp_rep_na_chr(CharacterVector xin, std::string rep);
RcppExport SEXP KaggleHouse_cpp_rep_na_chr(SEXP xinSEXP, SEXP repSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type xin(xinSEXP);
    Rcpp::traits::input_parameter< std::string >::type rep(repSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rep_na_chr(xin, rep));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bind
NumericMatrix cpp_bind(NumericVector a, NumericVector b);
RcppExport SEXP KaggleHouse_cpp_bind(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bind(a, b));
    return rcpp_result_gen;
END_RCPP
}
// cpp_valueOccurrencesToPoints
Rcpp::List cpp_valueOccurrencesToPoints(Rcpp::DataFrame x);
RcppExport SEXP KaggleHouse_cpp_valueOccurrencesToPoints(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_valueOccurrencesToPoints(x));
    return rcpp_result_gen;
END_RCPP
}
